name: Zig CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install Zig
      run: |
        wget https://ziglang.org/builds/zig-linux-x86_64-0.5.0+e6a812c82.tar.xz
      run: make test